site:
  title: Taymyr Antora UI
  url: /en
  start_page: ROOT::index.adoc
content:
  sources:
    - url: ./
      branches: HEAD
      start_paths: docs/en
ui:
  bundle:
    url: ./dist/ui-bundle.zip
    snapshot: true
  default_layout: docs

output:
  clean: false
  dir: build/site/en

antora:
  extensions:
    - require: '@antora/lunr-extension'
      languages: [en]
