name: Check

on:
  pull_request: # Check Pull Requests

  push:
    branches:
      - main # Check branch after merge

jobs:
  check:
    name: Check
    uses: ./.github/workflows/bundle.yml
    with:
      publish-pages: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

  finish:
    name: Finish
    needs: # Should be last
      - "check"
    uses: taymyr/.github/.github/workflows/rtm.yml@v1
