name: Generate documentation with Antora

on:
  workflow_call:
    inputs:
      upload:
        type: boolean
        required: false
        default: false
      publish-pages:
        type: boolean
        required: false
        default: false
jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install NPM dependencies
        run: npm ci --quiet --no-progress

      - name: Lint project
        run: npm run lint-project

      - name: Build bundle
        run: npx webpack

      - name: Generate example
        run: |
          npx antora antora-playbook-ru.yml
          npx antora antora-playbook-en.yml

      - name: Upload bundle
        if: inputs.upload
        uses: actions/upload-artifact@v3
        with:
          name: ui-bundle
          path: dist/ui-bundle.zip

      - name: Publish to GitHub Pages
        if: github.event.repository.fork == false && inputs.publish-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
          force_orphan: true
          cname: antora-ui.taymyr.io
          commit_message: "Deploy docs"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
